<?xml version="1.0" encoding="UTF-8"?>

<!--Escribir la DTD que permita validar el documento XML que se muestra a continuación. Hacer dos 
versiones en cada caso: DTD externa e interna.-->

<!DOCTYPE direccion
[
<!ELEMENT direccion (nombre, calle, ciudad,pais,codigo)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT codigo (#PCDATA)>
]>

<direccion>
    <nombre>Roberto García</nombre>
    <calle>c/ Mayor, 27</calle>
    <ciudad>Coslada</ciudad>
    <pais>España</pais>
    <codigo>39343</codigo>
</direccion>